### ISSUE TITLE
Cleanup work

### ISSUE THREAD

**Issue by devbysp** [devbysp/kcal-app#10]
## Description

During the experimentations were created _config entries_, _config files_ that are not used aymore. They are misleading / confusing and should be removed.

### Acceptance criterias

- [x] In the porject does not exist any file which is not used
- [x] In the configuration files does not exist any setting which is not justified.
 
## Todo
- [x] Make a list of files to clean up
- [x] Make a list of settings that are not justified
- [x] Remove db folder from backend
- [x] Backend env varables
- [x] Pass environment variable to frontend app
- [x] Replace port from endpoints-config.json with port from environments variables
- [x] Confiure microservices in compose.yaml using environment vars
- [x] Alternative test nginx.config file without microservice port  configuration
- [x] Remove from git --assume-notused files
