### ISSUE TITLE
Organize configuration

### ISSUE THREAD

**Issue by devbysp** [devbysp/kcal-app#9]
## Description

Each configuration should be done in a single place to avoid inconsistent settings.

### Acceptance criterias

- [x] Configurations are organized in a way that every setting (ports, bash paths, version) is done in a single place.

## Todo
- [x] Create a list of all confiurations
- [x] Create a plan of organizing the configurations
- [x] Implement the configurations
